export const CARS_PARTS = [
    {
        id: 'p1',
        carId: 'c1',
        name: 'Engine',
        description: 'BMW M20B25 2.5L inline-six engine for the E30 model.',
        cost: '2,500€',
    },
    {
        id: 'p2',
        carId: 'c1',
        name: 'Exhaust System',
        description: 'High-performance exhaust system to boost horsepower.',
        cost: '800€',
    },
    {
        id: 'p3',
        carId: 'c1',
        name: 'Suspension Kit',
        description: 'Bilstein B12 Pro-kit for improved handling.',
        cost: '1,100€',
    },
    {
        id: 'p4',
        carId: 'c1',
        name: 'Brake Discs',
        description: 'Zimmermann sport brake discs for the front wheels.',
        cost: '350€',
    },
    {
        id: 'p5',
        carId: 'c2',
        name: 'Clutch Kit',
        description: 'OEM clutch kit for Fiat 500, perfect for smooth shifting.',
        cost: '300€',
    },
    {
        id: 'p6',
        carId: 'c2',
        name: 'Air Filter',
        description: 'K&N high-flow air filter for increased engine efficiency.',
        cost: '50€',
    },
    {
        id: 'p7',
        carId: 'c2',
        name: 'Timing Belt',
        description: 'Contitech timing belt for Fiat 500 engine.',
        cost: '120€',
    },
    {
        id: 'p8',
        carId: 'c2',
        name: 'Alternator',
        description: 'Bosch alternator providing consistent electrical power.',
        cost: '400€',
    },
    {
        id: 'p9',
        carId: 'c3',
        name: 'Head Gasket',
        description: 'Elring head gasket for Fiat Panda engine sealing.',
        cost: '75€',
    },
    {
        id: 'p10',
        carId: 'c3',
        name: 'Shock Absorbers',
        description: 'KYB shock absorbers for improved ride comfort.',
        cost: '180€',
    },
    {
        id: 'p11',
        carId: 'c3',
        name: 'Battery',
        description: 'Varta Blue Dynamic battery for reliable starting power.',
        cost: '100€',
    },
    {
        id: 'p12',
        carId: 'c3',
        name: 'Radiator',
        description: 'Nissens radiator for effective engine cooling.',
        cost: '150€',
    },
    {
        id: 'p13',
        carId: 'c4',
        name: 'Turbocharger',
        description: 'Garrett turbocharger for the Ford Focus boosting performance.',
        cost: '1,200€',
    },
    {
        id: 'p14',
        carId: 'c4',
        name: 'Fuel Injectors',
        description: 'Bosch fuel injectors for efficient fuel delivery.',
        cost: '250€',
    },
    {
        id: 'p15',
        carId: 'c4',
        name: 'Brake Pads',
        description: 'EBC Greenstuff performance brake pads for front wheels.',
        cost: '90€',
    },
    {
        id: 'p16',
        carId: 'c4',
        name: 'Intercooler',
        description: 'Mishimoto performance intercooler for cooling intake air.',
        cost: '600€',
    },
    {
        id: 'p17',
        carId: 'c5',
        name: 'Exhaust Manifold',
        description: 'BBK ceramic-coated exhaust manifold for improved flow.',
        cost: '450€',
    },
    {
        id: 'p18',
        carId: 'c5',
        name: 'Cold Air Intake',
        description: 'K&N cold air intake for boosting Mustang’s power.',
        cost: '350€',
    },
    {
        id: 'p19',
        carId: 'c5',
        name: 'Performance Brakes',
        description: 'Brembo performance brake kit for high-speed stopping power.',
        cost: '1,500€',
    },
    {
        id: 'p20',
        carId: 'c5',
        name: 'Supercharger Kit',
        description: 'Roush supercharger kit for a massive power boost.',
        cost: '7,000€',
    },
    {
        id: 'p21',
        carId: 'c6',
        name: 'Timing Chain Kit',
        description: 'GM timing chain kit for Opel Astra’s engine.',
        cost: '400€',
    },
    {
        id: 'p22',
        carId: 'c6',
        name: 'Oil Pump',
        description: 'Pierburg oil pump for optimal lubrication.',
        cost: '150€',
    },
    {
        id: 'p23',
        carId: 'c6',
        name: 'Water Pump',
        description: 'Bosch water pump for efficient cooling in Astra.',
        cost: '90€',
    },
    {
        id: 'p24',
        carId: 'c6',
        name: 'Catalytic Converter',
        description: 'BM Catalysts catalytic converter for emissions control.',
        cost: '250€',
    },
    {
        id: 'p25',
        carId: 'c7',
        name: 'Differential',
        description: 'Subaru OEM rear differential for enhanced traction.',
        cost: '1,400€',
    },
    {
        id: 'p26',
        carId: 'c7',
        name: 'Turbocharger',
        description: 'IHI VF48 turbocharger for the WRX STI model.',
        cost: '1,800€',
    },
    {
        id: 'p27',
        carId: 'c7',
        name: 'Coilovers',
        description: 'Tein Flex Z coilovers for improved suspension performance.',
        cost: '950€',
    },
    {
        id: 'p28',
        carId: 'c7',
        name: 'Performance Clutch',
        description: 'Exedy performance clutch for high torque handling.',
        cost: '800€',
    },
    {
        id: 'p29',
        carId: 'c8',
        name: 'Sequential Transmission',
        description: 'HKS sequential transmission for lightning-fast shifts.',
        cost: '10,000€',
    },
    {
        id: 'p30',
        carId: 'c8',
        name: 'Carbon Fiber Hood',
        description: 'Seibon carbon fiber hood for weight reduction and style.',
        cost: '1,500€',
    },
    {
        id: 'p31',
        carId: 'c8',
        name: 'Turbo Kit',
        description: 'Greddy turbo kit for Toyota Supra to increase power.',
        cost: '3,000€',
    },
    {
        id: 'p32',
        carId: 'c8',
        name: 'Fuel Pump',
        description: 'Walbro 255LPH fuel pump for improved fuel delivery.',
        cost: '200€',
    },
    {
        id: 'p33',
        carId: 'c9',
        name: 'Carburetor',
        description: 'Solex carburetor for the classic Volkswagen Beetle engine.',
        cost: '250€',
    },
    {
        id: 'p34',
        carId: 'c9',
        name: 'Exhaust Muffler',
        description: 'Vintage-style exhaust muffler for Volkswagen Garbus.',
        cost: '150€',
    },
    {
        id: 'p35',
        carId: 'c9',
        name: 'Distributor',
        description: 'Bosch distributor for the air-cooled VW engine.',
        cost: '100€',
    },
    {
        id: 'p36',
        carId: 'c9',
        name: 'Ignition Coil',
        description: 'Beru ignition coil for reliable engine starts.',
        cost: '80€',
    },
    {
        id: 'p37',
        carId: 'c10',
        name: 'Drive Shaft',
        description: 'GKN drive shaft for front-wheel-drive Golf.',
        cost: '300€',
    },
    {
        id: 'p38',
        carId: 'c10',
        name: 'Control Arm',
        description: 'Lemforder control arm for precise handling.',
        cost: '120€',
    },
    {
        id: 'p39',
        carId: 'c10',
        name: 'Fuel Filter',
        description: 'Mann fuel filter for clean fuel supply.',
        cost: '25€',
    },
    {
        id: 'p40',
        carId: 'c10',
        name: 'Brake Rotors',
        description: 'Brembo front brake rotors for enhanced stopping power.',
        cost: '180€',
    }
];